# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: ubuntu:latest

variables:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_CONFIG: ${{ secrets.SSH_CONFIG }}

before_script:
  # - apt-get install python3.8
  - ls -l

deploy:
  stage: deploy
  script: 
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - export BUILDPACK_XTRACE=1
    - apt-get install -y git
    - git checkout $CI_COMMIT_SHA 
    - git remote -v
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # permissioning
    - eval "$(ssh-agent -s)" # setting ssh environment variable
    - echo '-----> Adding keys to ssh-agent'
    - ssh-add ~/.ssh/id_rsa
    - echo "$SSH_CONFIG" | base64 -d > ~/.ssh/config 
    - echo '-----> Adding git remote'
    - git config remote.plotly.url >&- || git remote add plotly dokku@$DASH_ENTERPRISE_HOST:$APP_NAME
    - echo '-----> Deploying app'
    - echo "$(git remote -v)"
    - echo "$(git branch)"
    - git checkout -b runner-branch
    - GIT_SSH_COMMAND='ssh -vvv' git push plotly runner-branch:main -f
  environment: production


