image: ubuntu:latest

pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Dash Enterprise'
        deployment: production
        trigger: 'automatic'
        script:
          - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
          - apt-get install -y git
          - git remote -v
          - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_ed25519
          - cat ~/.ssh/id_ed25519
          - chmod 600 ~/.ssh/id_ed25519 # permissioning
          - eval "$(ssh-agent -s)" # setting ssh environment variable
          - echo '-----> Adding keys to ssh-agent'
          - ssh-add ~/.ssh/id_ed25519
          - echo '-----> Adding git remote'
          - git config remote.plotly.url >&- || git remote add plotly git@$DE_HOST:$APP_NAME
          - echo '-----> Deploying app'
          - echo "$(git remote -v)"
          - echo "$(git branch)"
            # - git checkout -b runner-branch
          - GIT_SSH_COMMAND='ssh -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' git push plotly HEAD:main -f

